services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes: 
      - ./images:/app/images
    # Ports for testing purposes, remove before deploying bc we are using caddy to expose ports
    # ports:
    #   - 3000:3000
    depends_on:
      - db


  caddy:
    image: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
      # - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile