services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes: 
      - ~/data/lenslocked.com/images:/app/images
    # Ports for testing purposes, remove before deploying bc we are using caddy to expose ports
    # ports:
    #   - 3000:3000
    depends_on:
      - db


  caddy:
    image: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
      # - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ~/data/lenslocked.com/caddy:/data

  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}
    volumes:
      - ~/data/lenslocked.com/psql:/var/lib/postgresql/data/pgdata